### ISSUE TITLE
Error on template deployment

### ISSUE THREAD

**Issue by tagoad** [shibayan/containerapps-acmebot#21]
**Describe the bug**
When i try to create the deployment this error message gets kicked back by azure:

{
  "code": "InvalidTemplateDeployment",
  "details": [
    {
      "message": "Object reference not set to an instance of an object."
    }
  ],
  "message": "The template deployment 'Microsoft.Template-20220817155227' is not valid according to the validation procedure. The tracking id is '654a7dd2-bfcf-421c-9c62-bd65fa38de7c'. See inner errors for details."
}

**To Reproduce**
1: Click Deploy to Azure(Public)
2: Fill out fields
3: Review and Create

**Comment by shibayan** [comment]
I could not reproduce this issue. In terms of the error message, we think the problem is on the Azure side.

**Comment by tagoad** [comment]
Thank you for looking into it, it does seem to be azure. I tried creating with a different resource group and it worked just fine.
