### ISSUE TITLE
Error adding certificate

### ISSUE THREAD

**Issue by Garwakizashi** [shibayan/containerapps-acmebot#24]
**Describe the bug**
Trying to add a certificate, but it keeps giving a null reference exception:
```
Orchestrator function 'AddCertificate_Orchestrator' failed: The orchestrator function 'BindToContainerApp' failed: "The activity function 'ValidateDomain' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details.
```
Through app insights, I can see that it is failing at ValidateDomain at line `540`. The POST request to GetCustomHostNameAnalysis returns 200 as well. This may be something to do with Azure's SDK's `GetCustomHostNameAnalysisAsync` method perhaps?

**To Reproduce**
1. Deploy the acmebot
2. Go to the function app and add an entry
4. Error pop up as described.

**Environment (please complete the following information):**
 - Certificate Type: Sub-domain

**Additional context**
I've recently did 3 entries last week (18/19th August) and it worked well.
I've noticed you've also changed the Nuget package for some of the SDKs, I'm wondering if the breaking namespace change may have caused it to error?

**Comment by shibayan** [comment]
Thanks for the report.

This was caused by replacing the Azure Resource Manager SDK with the official version. Since this is a bug in the ARM SDK, we have temporarily added alternative code to address the issue.
