### ISSUE TITLE
Unable to deploy successfully

### ISSUE THREAD

**Issue by mile-abrettschneider** [shibayan/containerapps-acmebot#35]
**Describe the bug**
I'm currently trying to deploy this. My first problem was that I already have reached the limit os service plans in my subscription.
So I changed the template to reference an existing service plan.
While this worked I now got the error:
```{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"AppSetting with name 'Acmebot:SubscriptionId' is not allowed."}]}```

I then changed all "Acmebot:" to "Acmebot__" and it successfully deployed. I've set up authentication but now I'm stuck with  "The service is unavailable." and the portal says "Azure Functions runtime is unreachable"

**To Reproduce**
1. Try deploy with "Deploy to azure" button.

**Comment by shibayan** [comment]
If you are using a customized ARM Template, I cannot support it. Deployment is supported only on **Windows** Consumption or App Service Plan.

**Comment by mile-abrettschneider** [comment]
@shibayan Thanks. The hint with windows helped me.
