### ISSUE TITLE
Support setting container apps env custom dns suffix from wildcard certificate

### ISSUE THREAD

**Issue by mile-abrettschneider** [shibayan/containerapps-acmebot#36]
**Is your feature request related to a problem? Please describe.**
I hope I didn't miss anything but currently, as far as I can see, there is no support to set the container environment dns suffix via lets encrypt. While the bot supports creating wildcard certificates it's not yet able to assign them to the custom dns suffix.
The azure portal doesn't allow setting a custom dns suffix without providing a certificate.

It would be nice if the bot could add the dns suffix and upload the wildcard certificate for it aswell as auto update that certificate when needed without the need for each app to bind to that certificate.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/109420694/207581855-c5c28d56-cf6b-4075-9d0f-3396094b8fb4.png">

**Describe the solution you'd like**
Maybe a checkbox if a "*.domain" wildcard certificate is created, if the certificate (and dns suffix) should be added to the container app env.

Maybe like that:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/109420694/207586057-7af59a1a-d127-440b-b8d8-32b2ee497bfd.png">

**Comment by shibayan** [comment]
It would be wonderful if it could support custom DNS suffixes. Currently there does not seem to be a REST API or SDK available, so I would like to support this when the environment is ready.

**Comment by tpitman** [comment]
I don't know whether this issue is the same as something I would like to know, so before adding a new issue I thought I would ask.

My customer doesn't use Azure DNS for their DNS.

Is there a way to use this system without using Azure DNS? I am sure my customer will not be moving their DNS to Azure.

What can I do?

**Comment by mile-abrettschneider** [comment]
@tpitman It's a different issue but according to the readme Azure DNS is a requirement see:
https://github.com/shibayan/containerapps-acmebot#requirements

I think your issue would be similar to https://github.com/shibayan/containerapps-acmebot/issues/20

**Comment by tpitman** [comment]
Thank you.
