### ISSUE TITLE
DNS Zones and Container App in different Subscription

### ISSUE THREAD

**Issue by jhueppauff** [shibayan/containerapps-acmebot#48]
**Describe the bug**
It seems that DNS Zones and Container Apps can't be found, if they are located in a different subscription. 
Is there any option to configure the Subscription? 

**To Reproduce**
1. Place Function in Subscription A
2. Place Container Apps in Subscription B 
3. Place DNS Zones in Subscription C

**Comment by shibayan** [comment]
The option to specify separate subscription IDs for Container Apps and Azure DNS has not been implemented for simplicity; we are waiting for Container Apps to support import from Key Vault, which will be possible with another Acmebot.
