### ISSUE TITLE
Upload Failed Error | New Cert

### ISSUE THREAD

**Issue by kurt-west** [shibayan/containerapps-acmebot#65]
**Describe the bug**
Similar to #62 I get an Upload failed error; however, the certs end up being issued and installed in the Container App Env.
Access control is configured correctly and I have issues certs to the same environment. 

**To Reproduce**
Add new cert to environment.

**Environment (please complete the following information):**
 - Certificate Type: [e.g. Zone apex, Sub-domain, Wildcard]
Nested sub-domain and nested sub-domain wildcard

**Additional context**
Error details:
- System.NotImplementedException
- Azure.ResourceManager.AppContainers.AppContainersArmOperation`1.get_Id
- UploadCertificate

**Comment by shibayan** [comment]
Thanks for the report. We have identified the cause of this issue and a fix and release will follow shortly.
